// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zyx/bridge/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the bridge module's genesis state.
type GenesisState struct {
	Params       Params     `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	CallerList   []Caller   `protobuf:"bytes,2,rep,name=callerList,proto3" json:"callerList"`
	CallerCount  uint64     `protobuf:"varint,3,opt,name=callerCount,proto3" json:"callerCount,omitempty"`
	DepositList  []Deposit  `protobuf:"bytes,4,rep,name=depositList,proto3" json:"depositList"`
	WithdrawList []Withdraw `protobuf:"bytes,5,rep,name=withdrawList,proto3" json:"withdrawList"`
	SignerList   []Signer   `protobuf:"bytes,6,rep,name=signerList,proto3" json:"signerList"`
	SignerCount  uint64     `protobuf:"varint,7,opt,name=signerCount,proto3" json:"signerCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e178e0bee4bcb78, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetCallerList() []Caller {
	if m != nil {
		return m.CallerList
	}
	return nil
}

func (m *GenesisState) GetCallerCount() uint64 {
	if m != nil {
		return m.CallerCount
	}
	return 0
}

func (m *GenesisState) GetDepositList() []Deposit {
	if m != nil {
		return m.DepositList
	}
	return nil
}

func (m *GenesisState) GetWithdrawList() []Withdraw {
	if m != nil {
		return m.WithdrawList
	}
	return nil
}

func (m *GenesisState) GetSignerList() []Signer {
	if m != nil {
		return m.SignerList
	}
	return nil
}

func (m *GenesisState) GetSignerCount() uint64 {
	if m != nil {
		return m.SignerCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "zyx.bridge.GenesisState")
}

func init() { proto.RegisterFile("zyx/bridge/genesis.proto", fileDescriptor_8e178e0bee4bcb78) }

var fileDescriptor_8e178e0bee4bcb78 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x18, 0x84, 0xe3, 0xb6, 0x14, 0xc9, 0xe9, 0x64, 0x2a, 0x11, 0x3a, 0x98, 0x88, 0xa9, 0x03, 0x4a,
	0x10, 0x2c, 0x48, 0x48, 0x0c, 0x2d, 0x12, 0x0b, 0x03, 0x6a, 0x07, 0x24, 0xb6, 0x94, 0x58, 0xc1,
	0x52, 0x89, 0xa3, 0xd8, 0xa8, 0x4d, 0x9f, 0x82, 0xc7, 0xea, 0xd8, 0x91, 0x09, 0xa1, 0xe4, 0x19,
	0xd8, 0x51, 0xfc, 0x3b, 0xd4, 0x40, 0xb7, 0xd8, 0xdf, 0xdd, 0xe5, 0x3f, 0xff, 0xd8, 0x5b, 0x15,
	0xcb, 0x70, 0x96, 0xf3, 0x38, 0x61, 0x61, 0xc2, 0x52, 0x26, 0xb9, 0x0c, 0xb2, 0x5c, 0x28, 0x41,
	0xf0, 0xaa, 0x58, 0x06, 0x40, 0x06, 0xfd, 0x44, 0x24, 0x42, 0x5f, 0x87, 0xf5, 0x17, 0x28, 0x06,
	0x87, 0x96, 0x37, 0x8b, 0xf2, 0xe8, 0x45, 0xee, 0x00, 0x4f, 0xd1, 0x7c, 0xce, 0x72, 0x03, 0xec,
	0xbf, 0xc5, 0x2c, 0x13, 0x92, 0x2b, 0x43, 0x8e, 0x2c, 0xb2, 0xe0, 0xea, 0x39, 0xce, 0xa3, 0xc5,
	0x8e, 0x34, 0xc9, 0x93, 0xb4, 0x49, 0x3b, 0xf9, 0x6a, 0xe1, 0xde, 0x2d, 0xcc, 0x3c, 0x55, 0x91,
	0x62, 0xe4, 0x0c, 0x77, 0x61, 0x0e, 0x0f, 0xf9, 0x68, 0xe8, 0x9e, 0x93, 0x60, 0xdb, 0x21, 0xb8,
	0xd7, 0x64, 0xd4, 0x59, 0x7f, 0x1c, 0x3b, 0x13, 0xa3, 0x23, 0x97, 0x18, 0xc3, 0x80, 0x77, 0x5c,
	0x2a, 0xaf, 0xe5, 0xb7, 0xff, 0xba, 0xc6, 0x9a, 0x1a, 0x97, 0xa5, 0x25, 0x3e, 0x76, 0xe1, 0x34,
	0x16, 0xaf, 0xa9, 0xf2, 0xda, 0x3e, 0x1a, 0x76, 0x26, 0xf6, 0x15, 0xb9, 0xc2, 0xae, 0xe9, 0xa8,
	0xc3, 0x3b, 0x3a, 0xfc, 0xc0, 0x0e, 0xbf, 0x01, 0x6c, 0xd2, 0x6d, 0x35, 0xb9, 0xc6, 0xbd, 0xe6,
	0x19, 0xb4, 0x7b, 0x4f, 0xbb, 0xfb, 0xb6, 0xfb, 0xc1, 0x70, 0x63, 0xff, 0xa5, 0xaf, 0x8b, 0xc1,
	0x5b, 0x69, 0x77, 0xf7, 0x7f, 0xb1, 0xa9, 0xa6, 0x4d, 0xb1, 0xad, 0xb6, 0x2e, 0x06, 0x27, 0x28,
	0xb6, 0x0f, 0xc5, 0xac, 0xab, 0xd1, 0xe9, 0xba, 0xa4, 0x68, 0x53, 0x52, 0xf4, 0x59, 0x52, 0xf4,
	0x56, 0x51, 0x67, 0x53, 0x51, 0xe7, 0xbd, 0xa2, 0xce, 0x23, 0xa9, 0x57, 0xf5, 0xb3, 0x2c, 0x55,
	0x64, 0x4c, 0xce, 0xba, 0x7a, 0x59, 0x17, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xf6, 0x06,
	0xd8, 0x6a, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SignerCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SignerCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.SignerList) > 0 {
		for iNdEx := len(m.SignerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SignerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.WithdrawList) > 0 {
		for iNdEx := len(m.WithdrawList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WithdrawList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.DepositList) > 0 {
		for iNdEx := len(m.DepositList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.CallerCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CallerCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.CallerList) > 0 {
		for iNdEx := len(m.CallerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CallerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.CallerList) > 0 {
		for _, e := range m.CallerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CallerCount != 0 {
		n += 1 + sovGenesis(uint64(m.CallerCount))
	}
	if len(m.DepositList) > 0 {
		for _, e := range m.DepositList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WithdrawList) > 0 {
		for _, e := range m.WithdrawList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SignerList) > 0 {
		for _, e := range m.SignerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.SignerCount != 0 {
		n += 1 + sovGenesis(uint64(m.SignerCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallerList = append(m.CallerList, Caller{})
			if err := m.CallerList[len(m.CallerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallerCount", wireType)
			}
			m.CallerCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CallerCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositList = append(m.DepositList, Deposit{})
			if err := m.DepositList[len(m.DepositList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawList = append(m.WithdrawList, Withdraw{})
			if err := m.WithdrawList[len(m.WithdrawList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerList = append(m.SignerList, Signer{})
			if err := m.SignerList[len(m.SignerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerCount", wireType)
			}
			m.SignerCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
