// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ethermint/bridge/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the bridge module's genesis state.
type GenesisState struct {
	// params is the container of bridge module's parameters.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// deposit_list is the list of deposit records.
	DepositList []Deposit `protobuf:"bytes,2,rep,name=deposit_list,json=depositList,proto3" json:"deposit_list"`
	// withdraw_list is the list of withdraw records.
	WithdrawList []Withdraw `protobuf:"bytes,3,rep,name=withdraw_list,json=withdrawList,proto3" json:"withdraw_list"`
	// caller_group_list is the list of caller groups.
	CallerGroupList []CallerGroup `protobuf:"bytes,4,rep,name=caller_group_list,json=callerGroupList,proto3" json:"caller_group_list"`
	// signer_group_list is the list of signer groups.
	SignerGroupList []SignerGroup `protobuf:"bytes,5,rep,name=signer_group_list,json=signerGroupList,proto3" json:"signer_group_list"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_909f1e21b10ae95d, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetDepositList() []Deposit {
	if m != nil {
		return m.DepositList
	}
	return nil
}

func (m *GenesisState) GetWithdrawList() []Withdraw {
	if m != nil {
		return m.WithdrawList
	}
	return nil
}

func (m *GenesisState) GetCallerGroupList() []CallerGroup {
	if m != nil {
		return m.CallerGroupList
	}
	return nil
}

func (m *GenesisState) GetSignerGroupList() []SignerGroup {
	if m != nil {
		return m.SignerGroupList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "ethermint.bridge.v1.GenesisState")
}

func init() { proto.RegisterFile("ethermint/bridge/v1/genesis.proto", fileDescriptor_909f1e21b10ae95d) }

var fileDescriptor_909f1e21b10ae95d = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x31, 0x4f, 0x32, 0x31,
	0x18, 0xc7, 0xef, 0x5e, 0x78, 0x19, 0x0a, 0xc6, 0x78, 0x3a, 0x10, 0xd4, 0x7a, 0x32, 0x18, 0x5c,
	0xda, 0x80, 0x93, 0x2b, 0x68, 0x70, 0x70, 0x30, 0x30, 0x98, 0xb8, 0x90, 0x03, 0x9a, 0xd2, 0x84,
	0xa3, 0x97, 0xb6, 0x80, 0xae, 0x7e, 0x02, 0x3f, 0x16, 0x23, 0xa3, 0x93, 0x31, 0xf0, 0x45, 0xcc,
	0xb5, 0x3d, 0x0f, 0x4d, 0xe3, 0xd6, 0x3c, 0xf9, 0xfd, 0x7f, 0x7d, 0xda, 0x3f, 0x38, 0x27, 0x6a,
	0x42, 0x44, 0xcc, 0x66, 0x0a, 0x0f, 0x05, 0x1b, 0x53, 0x82, 0x17, 0x4d, 0x4c, 0xc9, 0x8c, 0x48,
	0x26, 0x51, 0x22, 0xb8, 0xe2, 0xc1, 0xe1, 0x37, 0x82, 0x0c, 0x82, 0x16, 0xcd, 0xda, 0x85, 0x2b,
	0x37, 0x8a, 0xa6, 0x53, 0x22, 0x06, 0x54, 0xf0, 0x79, 0x62, 0xc2, 0x35, 0xa7, 0x7f, 0x4c, 0x12,
	0x2e, 0x99, 0xb2, 0x48, 0xe8, 0x42, 0x92, 0x48, 0x44, 0xb1, 0xdd, 0xc0, 0x7d, 0x99, 0x64, 0x74,
	0xf6, 0xeb, 0xb2, 0xba, 0x8b, 0x5b, 0x32, 0x35, 0x19, 0x8b, 0x68, 0x69, 0x99, 0x23, 0xca, 0x29,
	0xd7, 0x47, 0x9c, 0x9e, 0xcc, 0xb4, 0xfe, 0x5a, 0x00, 0x95, 0xae, 0x79, 0x75, 0x5f, 0x45, 0x8a,
	0x04, 0xd7, 0xa0, 0x64, 0x56, 0xa8, 0xfa, 0xa1, 0xdf, 0x28, 0xb7, 0x8e, 0x91, 0xe3, 0x17, 0xd0,
	0x83, 0x46, 0xda, 0xc5, 0xd5, 0xc7, 0x99, 0xd7, 0xb3, 0x81, 0xe0, 0x16, 0x54, 0xec, 0x03, 0x07,
	0x53, 0x26, 0x55, 0xf5, 0x5f, 0x58, 0x68, 0x94, 0x5b, 0x27, 0x4e, 0xc1, 0x8d, 0x01, 0xad, 0xa1,
	0x6c, 0x73, 0xf7, 0x4c, 0xaa, 0xe0, 0x0e, 0xec, 0x65, 0xab, 0x1b, 0x4f, 0x41, 0x7b, 0x4e, 0x9d,
	0x9e, 0x47, 0x4b, 0x5a, 0x51, 0x25, 0x4b, 0x6a, 0x53, 0x0f, 0x1c, 0xec, 0x36, 0x63, 0x6c, 0x45,
	0x6d, 0x0b, 0x9d, 0xb6, 0x8e, 0xa6, 0xbb, 0x29, 0x6c, 0x85, 0xfb, 0xa3, 0x7c, 0x94, 0x39, 0x77,
	0x0b, 0x30, 0xce, 0xff, 0x7f, 0x38, 0xfb, 0x9a, 0xfe, 0xe1, 0x94, 0xf9, 0x28, 0x75, 0xb6, 0x3b,
	0xab, 0x0d, 0xf4, 0xd7, 0x1b, 0xe8, 0x7f, 0x6e, 0xa0, 0xff, 0xb6, 0x85, 0xde, 0x7a, 0x0b, 0xbd,
	0xf7, 0x2d, 0xf4, 0x9e, 0x2e, 0x29, 0x53, 0x93, 0xf9, 0x10, 0x8d, 0x78, 0x8c, 0xc9, 0x22, 0xe6,
	0x12, 0xe7, 0x4d, 0x3f, 0x67, 0x5d, 0xab, 0x97, 0x84, 0xc8, 0x61, 0x49, 0x17, 0x7a, 0xf5, 0x15,
	0x00, 0x00, 0xff, 0xff, 0xba, 0x62, 0xab, 0x27, 0xd9, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignerGroupList) > 0 {
		for iNdEx := len(m.SignerGroupList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SignerGroupList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.CallerGroupList) > 0 {
		for iNdEx := len(m.CallerGroupList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CallerGroupList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.WithdrawList) > 0 {
		for iNdEx := len(m.WithdrawList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WithdrawList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.DepositList) > 0 {
		for iNdEx := len(m.DepositList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.DepositList) > 0 {
		for _, e := range m.DepositList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.WithdrawList) > 0 {
		for _, e := range m.WithdrawList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CallerGroupList) > 0 {
		for _, e := range m.CallerGroupList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SignerGroupList) > 0 {
		for _, e := range m.SignerGroupList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositList = append(m.DepositList, Deposit{})
			if err := m.DepositList[len(m.DepositList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawList = append(m.WithdrawList, Withdraw{})
			if err := m.WithdrawList[len(m.WithdrawList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallerGroupList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallerGroupList = append(m.CallerGroupList, CallerGroup{})
			if err := m.CallerGroupList[len(m.CallerGroupList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerGroupList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerGroupList = append(m.SignerGroupList, SignerGroup{})
			if err := m.SignerGroupList[len(m.SignerGroupList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
