// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ethermint/types/v1/bitcoin_indexer.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BitcoinTxParseResult is the value parsed bitcoin transaction
// NOTE: This struct may be extended in the future
type BitcoinTxParseResult struct {
	// from is l2 user address, by parse bitcoin get the address
	From []string `protobuf:"bytes,1,rep,name=from,proto3" json:"from,omitempty"`
	// to is listening address
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// value is from transfer amount
	Value int64 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	// tx_id is the btc transaction id
	TxId string `protobuf:"bytes,4,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	// tx_type is the type of the transaction, eg. "brc20_transfer","transfer"
	TxType string `protobuf:"bytes,5,opt,name=tx_type,json=txType,proto3" json:"tx_type,omitempty"`
	// index is the index of the transaction in the block
	Index int64 `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *BitcoinTxParseResult) Reset()         { *m = BitcoinTxParseResult{} }
func (m *BitcoinTxParseResult) String() string { return proto.CompactTextString(m) }
func (*BitcoinTxParseResult) ProtoMessage()    {}
func (*BitcoinTxParseResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a28da31cd1817aa6, []int{0}
}
func (m *BitcoinTxParseResult) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BitcoinTxParseResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BitcoinTxParseResult.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BitcoinTxParseResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitcoinTxParseResult.Merge(m, src)
}
func (m *BitcoinTxParseResult) XXX_Size() int {
	return m.Size()
}
func (m *BitcoinTxParseResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BitcoinTxParseResult.DiscardUnknown(m)
}

var xxx_messageInfo_BitcoinTxParseResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BitcoinTxParseResult)(nil), "ethermint.types.v1.BitcoinTxParseResult")
}

func init() {
	proto.RegisterFile("ethermint/types/v1/bitcoin_indexer.proto", fileDescriptor_a28da31cd1817aa6)
}

var fileDescriptor_a28da31cd1817aa6 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xe3, 0xfc, 0x43, 0xf5, 0xc0, 0x60, 0x22, 0x61, 0x31, 0x98, 0x88, 0x29, 0x53, 0xac,
	0x8a, 0xad, 0x63, 0x37, 0x36, 0x14, 0x75, 0x62, 0x89, 0x9a, 0xc6, 0xa4, 0x96, 0x9a, 0x38, 0x72,
	0x2e, 0x91, 0xfb, 0x0d, 0x18, 0x99, 0x99, 0xf8, 0x38, 0x8c, 0x1d, 0x19, 0x51, 0xf2, 0x45, 0x50,
	0x1c, 0x89, 0x81, 0xed, 0xbd, 0xbb, 0x9f, 0x9e, 0xde, 0x1d, 0x4e, 0x04, 0x1c, 0x85, 0xae, 0x65,
	0x03, 0x1c, 0xce, 0xad, 0xe8, 0xf8, 0xb0, 0xe6, 0x85, 0x84, 0x83, 0x92, 0x4d, 0x2e, 0x9b, 0x52,
	0x18, 0xa1, 0xd3, 0x56, 0x2b, 0x50, 0x84, 0xfc, 0x91, 0xa9, 0x25, 0xd3, 0x61, 0x7d, 0x17, 0x55,
	0xaa, 0x52, 0x76, 0xcd, 0x67, 0xb5, 0x90, 0x0f, 0x1f, 0x08, 0x47, 0xdb, 0x25, 0x63, 0x67, 0x9e,
	0xf7, 0xba, 0x13, 0x99, 0xe8, 0xfa, 0x13, 0x10, 0x82, 0xfd, 0x57, 0xad, 0x6a, 0x8a, 0x62, 0x2f,
	0x59, 0x65, 0x56, 0x93, 0x6b, 0xec, 0x82, 0xa2, 0x6e, 0x8c, 0x92, 0x55, 0xe6, 0x82, 0x22, 0x11,
	0x0e, 0x86, 0xfd, 0xa9, 0x17, 0xd4, 0x8b, 0x51, 0xe2, 0x65, 0x8b, 0x21, 0x37, 0x38, 0x00, 0x93,
	0xcb, 0x92, 0xfa, 0x16, 0xf4, 0xc1, 0x3c, 0x95, 0xe4, 0x16, 0x5f, 0x81, 0xc9, 0xe7, 0x32, 0x34,
	0xb0, 0xe3, 0x10, 0xcc, 0xee, 0xdc, 0x8a, 0x39, 0xc3, 0x76, 0xa7, 0xe1, 0x92, 0x61, 0xcd, 0xc6,
	0x7f, 0xfb, 0xbc, 0x77, 0xb6, 0x9b, 0xaf, 0x91, 0xa1, 0xcb, 0xc8, 0xd0, 0xcf, 0xc8, 0xd0, 0xfb,
	0xc4, 0x9c, 0xcb, 0xc4, 0x9c, 0xef, 0x89, 0x39, 0x2f, 0x71, 0x25, 0xe1, 0xd8, 0x17, 0xe9, 0x41,
	0xd5, 0x5c, 0x0c, 0xb5, 0xea, 0xf8, 0xbf, 0xdf, 0x14, 0xa1, 0xbd, 0xef, 0xf1, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x74, 0x78, 0x7e, 0x0c, 0x35, 0x01, 0x00, 0x00,
}

func (m *BitcoinTxParseResult) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BitcoinTxParseResult) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BitcoinTxParseResult) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Index != 0 {
		i = encodeVarintBitcoinIndexer(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x30
	}
	if len(m.TxType) > 0 {
		i -= len(m.TxType)
		copy(dAtA[i:], m.TxType)
		i = encodeVarintBitcoinIndexer(dAtA, i, uint64(len(m.TxType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintBitcoinIndexer(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0x22
	}
	if m.Value != 0 {
		i = encodeVarintBitcoinIndexer(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x18
	}
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintBitcoinIndexer(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.From) > 0 {
		for iNdEx := len(m.From) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.From[iNdEx])
			copy(dAtA[i:], m.From[iNdEx])
			i = encodeVarintBitcoinIndexer(dAtA, i, uint64(len(m.From[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintBitcoinIndexer(dAtA []byte, offset int, v uint64) int {
	offset -= sovBitcoinIndexer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BitcoinTxParseResult) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.From) > 0 {
		for _, s := range m.From {
			l = len(s)
			n += 1 + l + sovBitcoinIndexer(uint64(l))
		}
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovBitcoinIndexer(uint64(l))
	}
	if m.Value != 0 {
		n += 1 + sovBitcoinIndexer(uint64(m.Value))
	}
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovBitcoinIndexer(uint64(l))
	}
	l = len(m.TxType)
	if l > 0 {
		n += 1 + l + sovBitcoinIndexer(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovBitcoinIndexer(uint64(m.Index))
	}
	return n
}

func sovBitcoinIndexer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBitcoinIndexer(x uint64) (n int) {
	return sovBitcoinIndexer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BitcoinTxParseResult) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBitcoinIndexer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BitcoinTxParseResult: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BitcoinTxParseResult: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBitcoinIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBitcoinIndexer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = append(m.From, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBitcoinIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBitcoinIndexer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBitcoinIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBitcoinIndexer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBitcoinIndexer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBitcoinIndexer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBitcoinIndexer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBitcoinIndexer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBitcoinIndexer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBitcoinIndexer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBitcoinIndexer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBitcoinIndexer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBitcoinIndexer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBitcoinIndexer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBitcoinIndexer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBitcoinIndexer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBitcoinIndexer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBitcoinIndexer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBitcoinIndexer = fmt.Errorf("proto: unexpected end of group")
)
