// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ethermint/committer/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitProof defines proof msg to be submitted by a committer.
type MsgSubmitProof struct {
	// id is the unique identifier of the proposal.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// from is the address of the committer which submits the proposal.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// proof_hash is the hash of the batch proof.
	ProofHash string `protobuf:"bytes,3,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`
	// state_root_hash is the hash of the state root.
	StateRootHash string `protobuf:"bytes,4,opt,name=state_root_hash,json=stateRootHash,proto3" json:"state_root_hash,omitempty"`
	// start_index is the start index of the batch proof.
	StartIndex uint64 `protobuf:"varint,5,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	// end_index is the end index of the batch proof.
	EndIndex uint64 `protobuf:"varint,6,opt,name=end_index,json=endIndex,proto3" json:"end_index,omitempty"`
}

func (m *MsgSubmitProof) Reset()         { *m = MsgSubmitProof{} }
func (m *MsgSubmitProof) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitProof) ProtoMessage()    {}
func (*MsgSubmitProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{0}
}
func (m *MsgSubmitProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitProof.Merge(m, src)
}
func (m *MsgSubmitProof) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitProof) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitProof.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitProof proto.InternalMessageInfo

// MsgSubmitProofResponse defines response for MsgSubmitProof.
type MsgSubmitProofResponse struct {
	// id is the unique identifier of the proposal.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgSubmitProofResponse) Reset()         { *m = MsgSubmitProofResponse{} }
func (m *MsgSubmitProofResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitProofResponse) ProtoMessage()    {}
func (*MsgSubmitProofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{1}
}
func (m *MsgSubmitProofResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitProofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitProofResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitProofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitProofResponse.Merge(m, src)
}
func (m *MsgSubmitProofResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitProofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitProofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitProofResponse proto.InternalMessageInfo

// MsgBitcoinTx defines the bicoin taproot tx hash to be submitted by a committer.
type MsgBitcoinTx struct {
	// id is the unique identifier of the proposal.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// from is the address of the committer which submits the proposal.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// bitcoin_tx_hash is the hash of the taproot transaction.
	BitcoinTxHash string `protobuf:"bytes,3,opt,name=bitcoin_tx_hash,json=bitcoinTxHash,proto3" json:"bitcoin_tx_hash,omitempty"`
}

func (m *MsgBitcoinTx) Reset()         { *m = MsgBitcoinTx{} }
func (m *MsgBitcoinTx) String() string { return proto.CompactTextString(m) }
func (*MsgBitcoinTx) ProtoMessage()    {}
func (*MsgBitcoinTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{2}
}
func (m *MsgBitcoinTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBitcoinTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBitcoinTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBitcoinTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBitcoinTx.Merge(m, src)
}
func (m *MsgBitcoinTx) XXX_Size() int {
	return m.Size()
}
func (m *MsgBitcoinTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBitcoinTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBitcoinTx proto.InternalMessageInfo

// MsgBitcoinTxResponse defines response for MsgBitcoinTx.
type MsgBitcoinTxResponse struct {
	// id is the unique identifier of the proposal.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgBitcoinTxResponse) Reset()         { *m = MsgBitcoinTxResponse{} }
func (m *MsgBitcoinTxResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBitcoinTxResponse) ProtoMessage()    {}
func (*MsgBitcoinTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{3}
}
func (m *MsgBitcoinTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBitcoinTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBitcoinTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBitcoinTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBitcoinTxResponse.Merge(m, src)
}
func (m *MsgBitcoinTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBitcoinTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBitcoinTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBitcoinTxResponse proto.InternalMessageInfo

// MsgTimeoutProposal defines the timeout proposal msg to be submitted by a committer.
type MsgTimeoutProposal struct {
	// id is the unique identifier of the proposal.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// from is the address of the committer which submits the proposal.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
}

func (m *MsgTimeoutProposal) Reset()         { *m = MsgTimeoutProposal{} }
func (m *MsgTimeoutProposal) String() string { return proto.CompactTextString(m) }
func (*MsgTimeoutProposal) ProtoMessage()    {}
func (*MsgTimeoutProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{4}
}
func (m *MsgTimeoutProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTimeoutProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTimeoutProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTimeoutProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTimeoutProposal.Merge(m, src)
}
func (m *MsgTimeoutProposal) XXX_Size() int {
	return m.Size()
}
func (m *MsgTimeoutProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTimeoutProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTimeoutProposal proto.InternalMessageInfo

// MsgTimeoutProposalResponse defines the response for MsgTimeoutProposal.
type MsgTimeoutProposalResponse struct {
	// id is the unique identifier of the proposal.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgTimeoutProposalResponse) Reset()         { *m = MsgTimeoutProposalResponse{} }
func (m *MsgTimeoutProposalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTimeoutProposalResponse) ProtoMessage()    {}
func (*MsgTimeoutProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{5}
}
func (m *MsgTimeoutProposalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTimeoutProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTimeoutProposalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTimeoutProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTimeoutProposalResponse.Merge(m, src)
}
func (m *MsgTimeoutProposalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTimeoutProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTimeoutProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTimeoutProposalResponse proto.InternalMessageInfo

// MsgAddCommitter defines the msg to be submitted by a committer.
type MsgAddCommitter struct {
	// from is the address of the committer which submits the proposal.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// committer is the address of the committer which will be added.
	Committer string `protobuf:"bytes,2,opt,name=committer,proto3" json:"committer,omitempty"`
}

func (m *MsgAddCommitter) Reset()         { *m = MsgAddCommitter{} }
func (m *MsgAddCommitter) String() string { return proto.CompactTextString(m) }
func (*MsgAddCommitter) ProtoMessage()    {}
func (*MsgAddCommitter) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{6}
}
func (m *MsgAddCommitter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddCommitter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddCommitter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddCommitter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddCommitter.Merge(m, src)
}
func (m *MsgAddCommitter) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddCommitter) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddCommitter.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddCommitter proto.InternalMessageInfo

// MsgAddCommitterResponse defines the response for MsgAddCommitter.
type MsgAddCommitterResponse struct {
	// committer is the address of the committer which has been added.
	Committer string `protobuf:"bytes,1,opt,name=committer,proto3" json:"committer,omitempty"`
}

func (m *MsgAddCommitterResponse) Reset()         { *m = MsgAddCommitterResponse{} }
func (m *MsgAddCommitterResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddCommitterResponse) ProtoMessage()    {}
func (*MsgAddCommitterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{7}
}
func (m *MsgAddCommitterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddCommitterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddCommitterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddCommitterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddCommitterResponse.Merge(m, src)
}
func (m *MsgAddCommitterResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddCommitterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddCommitterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddCommitterResponse proto.InternalMessageInfo

// MsgRemoveCommitter defines the msg to be submitted by a committer.
type MsgRemoveCommitter struct {
	// from is the address of the committer which submits the proposal.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// committer is the address of the committer which will be removed.
	Committer string `protobuf:"bytes,2,opt,name=committer,proto3" json:"committer,omitempty"`
}

func (m *MsgRemoveCommitter) Reset()         { *m = MsgRemoveCommitter{} }
func (m *MsgRemoveCommitter) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveCommitter) ProtoMessage()    {}
func (*MsgRemoveCommitter) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{8}
}
func (m *MsgRemoveCommitter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveCommitter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveCommitter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveCommitter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveCommitter.Merge(m, src)
}
func (m *MsgRemoveCommitter) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveCommitter) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveCommitter.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveCommitter proto.InternalMessageInfo

// MsgRemoveCommitterResponse defines the response for MsgRemoveCommitter.
type MsgRemoveCommitterResponse struct {
	// committer is the address of the committer which has been removed.
	Committer string `protobuf:"bytes,1,opt,name=committer,proto3" json:"committer,omitempty"`
}

func (m *MsgRemoveCommitterResponse) Reset()         { *m = MsgRemoveCommitterResponse{} }
func (m *MsgRemoveCommitterResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveCommitterResponse) ProtoMessage()    {}
func (*MsgRemoveCommitterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_525de3b0c6213031, []int{9}
}
func (m *MsgRemoveCommitterResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveCommitterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveCommitterResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveCommitterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveCommitterResponse.Merge(m, src)
}
func (m *MsgRemoveCommitterResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveCommitterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveCommitterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveCommitterResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitProof)(nil), "evmos.ethermint.committer.MsgSubmitProof")
	proto.RegisterType((*MsgSubmitProofResponse)(nil), "evmos.ethermint.committer.MsgSubmitProofResponse")
	proto.RegisterType((*MsgBitcoinTx)(nil), "evmos.ethermint.committer.MsgBitcoinTx")
	proto.RegisterType((*MsgBitcoinTxResponse)(nil), "evmos.ethermint.committer.MsgBitcoinTxResponse")
	proto.RegisterType((*MsgTimeoutProposal)(nil), "evmos.ethermint.committer.MsgTimeoutProposal")
	proto.RegisterType((*MsgTimeoutProposalResponse)(nil), "evmos.ethermint.committer.MsgTimeoutProposalResponse")
	proto.RegisterType((*MsgAddCommitter)(nil), "evmos.ethermint.committer.MsgAddCommitter")
	proto.RegisterType((*MsgAddCommitterResponse)(nil), "evmos.ethermint.committer.MsgAddCommitterResponse")
	proto.RegisterType((*MsgRemoveCommitter)(nil), "evmos.ethermint.committer.MsgRemoveCommitter")
	proto.RegisterType((*MsgRemoveCommitterResponse)(nil), "evmos.ethermint.committer.MsgRemoveCommitterResponse")
}

func init() { proto.RegisterFile("ethermint/committer/tx.proto", fileDescriptor_525de3b0c6213031) }

var fileDescriptor_525de3b0c6213031 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0x33, 0x69, 0x5a, 0x7d, 0xb9, 0xfd, 0x13, 0xc9, 0xea, 0x47, 0x83, 0x9b, 0xba, 0x91,
	0x91, 0x42, 0xa9, 0x8a, 0x2d, 0x82, 0xd8, 0x54, 0x02, 0x41, 0x91, 0x10, 0x95, 0x88, 0x84, 0x42,
	0x57, 0x6c, 0x8c, 0x53, 0x4f, 0x9d, 0x91, 0x6a, 0x8f, 0xe5, 0x99, 0x54, 0x61, 0xcb, 0x06, 0x76,
	0x20, 0xf5, 0x01, 0xe0, 0x4d, 0xd8, 0xb2, 0xac, 0xc4, 0x86, 0x25, 0x4a, 0x78, 0x0b, 0x36, 0xc8,
	0x37, 0x8e, 0xe3, 0x98, 0x36, 0x71, 0xc5, 0xce, 0x9a, 0xf9, 0xdd, 0x39, 0xe7, 0xde, 0x9c, 0xc9,
	0x40, 0x8d, 0xca, 0x2e, 0x0d, 0x3d, 0xe6, 0x4b, 0xf3, 0x98, 0x7b, 0x1e, 0x93, 0x92, 0x86, 0xa6,
	0xec, 0x1b, 0x41, 0xc8, 0x25, 0x57, 0x6e, 0xd2, 0x33, 0x8f, 0x0b, 0x23, 0x61, 0x8c, 0x84, 0x51,
	0xd7, 0x5d, 0xee, 0x72, 0xa4, 0xcc, 0xe8, 0x6b, 0x54, 0xa0, 0xd6, 0x5c, 0xce, 0xdd, 0x53, 0x6a,
	0xda, 0x01, 0x33, 0x6d, 0xdf, 0xe7, 0xd2, 0x96, 0x8c, 0xfb, 0x62, 0xb4, 0xab, 0x7f, 0x25, 0xb0,
	0xd6, 0x12, 0xee, 0xab, 0x5e, 0xc7, 0x63, 0xf2, 0x65, 0xc8, 0xf9, 0x89, 0xb2, 0x06, 0x45, 0xe6,
	0x54, 0x49, 0x9d, 0xec, 0x94, 0xda, 0x45, 0xe6, 0x28, 0x0a, 0x94, 0x4e, 0x42, 0xee, 0x55, 0x8b,
	0x75, 0xb2, 0x53, 0x6e, 0xe3, 0xb7, 0xb2, 0x05, 0x10, 0x44, 0xb0, 0xd5, 0xb5, 0x45, 0xb7, 0xba,
	0x80, 0x3b, 0x65, 0x5c, 0x79, 0x6e, 0x8b, 0xae, 0xd2, 0x80, 0x8a, 0x90, 0xb6, 0xa4, 0x56, 0xc8,
	0xb9, 0x1c, 0x31, 0x25, 0x64, 0x56, 0x71, 0xb9, 0xcd, 0xb9, 0x44, 0x6e, 0x1b, 0x96, 0x85, 0xb4,
	0x43, 0x69, 0x31, 0xdf, 0xa1, 0xfd, 0xea, 0x22, 0x6a, 0x02, 0x2e, 0x1d, 0x46, 0x2b, 0xca, 0x26,
	0x94, 0xa9, 0xef, 0xc4, 0xdb, 0x4b, 0xb8, 0xfd, 0x1f, 0xf5, 0x1d, 0xdc, 0xdc, 0x2f, 0x7d, 0xf8,
	0xb2, 0x5d, 0xd0, 0x0d, 0xb8, 0x31, 0xdd, 0x40, 0x9b, 0x8a, 0x80, 0xfb, 0x82, 0x66, 0x1b, 0x89,
	0xf9, 0x37, 0xb0, 0xd2, 0x12, 0xee, 0x01, 0x93, 0xc7, 0x9c, 0xf9, 0x47, 0xfd, 0x5c, 0xed, 0x36,
	0xa0, 0xd2, 0x19, 0x15, 0x58, 0xb2, 0x9f, 0xee, 0x79, 0xb5, 0x33, 0x3e, 0x27, 0xea, 0x27, 0x56,
	0xd8, 0x83, 0xf5, 0xb4, 0xc2, 0x1c, 0x3f, 0x8f, 0x40, 0x69, 0x09, 0xf7, 0x88, 0x79, 0x94, 0xf7,
	0xa2, 0x06, 0x02, 0x2e, 0xec, 0xd3, 0x3c, 0xae, 0xe2, 0xfa, 0x26, 0xa8, 0x7f, 0xd7, 0xcf, 0xd1,
	0x3c, 0x84, 0x4a, 0x4b, 0xb8, 0x4f, 0x1c, 0xe7, 0xe9, 0x38, 0x3c, 0x89, 0x00, 0x49, 0xb5, 0x5d,
	0x83, 0x72, 0x92, 0xae, 0x58, 0x79, 0xb2, 0x10, 0x1f, 0xf5, 0x10, 0x36, 0x32, 0x47, 0x25, 0xda,
	0x53, 0xe5, 0xe4, 0xf2, 0xf2, 0x17, 0xd8, 0x7d, 0x9b, 0x7a, 0xfc, 0x8c, 0xfe, 0xbb, 0x99, 0xc7,
	0x38, 0x8b, 0xcc, 0x69, 0xd7, 0xf1, 0xd3, 0xfc, 0xbd, 0x08, 0x0b, 0x2d, 0xe1, 0x2a, 0x1f, 0x09,
	0x2c, 0xa7, 0x2f, 0xc5, 0x1d, 0xe3, 0xca, 0x7b, 0x67, 0x4c, 0xc7, 0x4f, 0xbd, 0x97, 0x1b, 0x1d,
	0x3b, 0xd3, 0xf5, 0x77, 0xdf, 0x7f, 0x9d, 0x17, 0x6b, 0xfa, 0x46, 0xea, 0xc6, 0x0b, 0xe4, 0x2c,
	0xbc, 0x54, 0xfb, 0x64, 0x57, 0x79, 0x4f, 0xa0, 0x3c, 0x49, 0xed, 0xed, 0xd9, 0x22, 0x09, 0xa8,
	0x9a, 0x39, 0xc1, 0xc4, 0x4b, 0x1d, 0xbd, 0xa8, 0xfa, 0xff, 0x29, 0x2f, 0x93, 0xf0, 0x47, 0x4e,
	0x3e, 0x13, 0xa8, 0x64, 0xf3, 0x7a, 0x77, 0xb6, 0x4c, 0x06, 0x57, 0x1f, 0x5c, 0x0b, 0x4f, 0xbc,
	0x35, 0xd0, 0x5b, 0x5d, 0xdf, 0x4c, 0xff, 0x33, 0x8e, 0xd8, 0x68, 0x50, 0x08, 0x47, 0x0e, 0xcf,
	0x09, 0xac, 0x4c, 0xa5, 0x7b, 0x77, 0xb6, 0x5e, 0x9a, 0x55, 0x9b, 0xf9, 0xd9, 0xc4, 0xd8, 0x2d,
	0x34, 0xb6, 0xa5, 0x57, 0x53, 0xc6, 0x6c, 0xc7, 0xb1, 0x26, 0xf1, 0x8a, 0xe7, 0x96, 0x4d, 0xfa,
	0x9c, 0xb9, 0x65, 0xf0, 0x79, 0x73, 0xbb, 0x22, 0xf9, 0x97, 0xce, 0x2d, 0x44, 0x76, 0xca, 0xe1,
	0xc1, 0xb3, 0x6f, 0x03, 0x8d, 0x5c, 0x0c, 0x34, 0xf2, 0x73, 0xa0, 0x91, 0x4f, 0x43, 0xad, 0x70,
	0x31, 0xd4, 0x0a, 0x3f, 0x86, 0x5a, 0xe1, 0xf5, 0x9e, 0xcb, 0x64, 0xb7, 0xd7, 0x89, 0xe4, 0x4c,
	0xb4, 0x60, 0x4e, 0x5e, 0xa9, 0x7e, 0xfa, 0xd7, 0x78, 0x1b, 0x50, 0xd1, 0x59, 0xc2, 0xc7, 0xe5,
	0xfe, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0xc2, 0x82, 0xc5, 0xcb, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubmitProof defines a method for a committer to submit a batch proof.
	SubmitProof(ctx context.Context, in *MsgSubmitProof, opts ...grpc.CallOption) (*MsgSubmitProofResponse, error)
	// BitcoinTx defines a method for a committer to commit a bitcoin tx hash.
	BitcoinTx(ctx context.Context, in *MsgBitcoinTx, opts ...grpc.CallOption) (*MsgBitcoinTxResponse, error)
	// TimeoutProposal defines a method for a committer to timeout a proposal.
	TimeoutProposal(ctx context.Context, in *MsgTimeoutProposal, opts ...grpc.CallOption) (*MsgTimeoutProposalResponse, error)
	// AddCommitter defines a method for a committer to add a committer.
	AddCommitter(ctx context.Context, in *MsgAddCommitter, opts ...grpc.CallOption) (*MsgAddCommitterResponse, error)
	// RemoveCommitter defines a method for a committer to remove a committer.
	RemoveCommitter(ctx context.Context, in *MsgRemoveCommitter, opts ...grpc.CallOption) (*MsgRemoveCommitterResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitProof(ctx context.Context, in *MsgSubmitProof, opts ...grpc.CallOption) (*MsgSubmitProofResponse, error) {
	out := new(MsgSubmitProofResponse)
	err := c.cc.Invoke(ctx, "/evmos.ethermint.committer.Msg/SubmitProof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BitcoinTx(ctx context.Context, in *MsgBitcoinTx, opts ...grpc.CallOption) (*MsgBitcoinTxResponse, error) {
	out := new(MsgBitcoinTxResponse)
	err := c.cc.Invoke(ctx, "/evmos.ethermint.committer.Msg/BitcoinTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TimeoutProposal(ctx context.Context, in *MsgTimeoutProposal, opts ...grpc.CallOption) (*MsgTimeoutProposalResponse, error) {
	out := new(MsgTimeoutProposalResponse)
	err := c.cc.Invoke(ctx, "/evmos.ethermint.committer.Msg/TimeoutProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddCommitter(ctx context.Context, in *MsgAddCommitter, opts ...grpc.CallOption) (*MsgAddCommitterResponse, error) {
	out := new(MsgAddCommitterResponse)
	err := c.cc.Invoke(ctx, "/evmos.ethermint.committer.Msg/AddCommitter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveCommitter(ctx context.Context, in *MsgRemoveCommitter, opts ...grpc.CallOption) (*MsgRemoveCommitterResponse, error) {
	out := new(MsgRemoveCommitterResponse)
	err := c.cc.Invoke(ctx, "/evmos.ethermint.committer.Msg/RemoveCommitter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubmitProof defines a method for a committer to submit a batch proof.
	SubmitProof(context.Context, *MsgSubmitProof) (*MsgSubmitProofResponse, error)
	// BitcoinTx defines a method for a committer to commit a bitcoin tx hash.
	BitcoinTx(context.Context, *MsgBitcoinTx) (*MsgBitcoinTxResponse, error)
	// TimeoutProposal defines a method for a committer to timeout a proposal.
	TimeoutProposal(context.Context, *MsgTimeoutProposal) (*MsgTimeoutProposalResponse, error)
	// AddCommitter defines a method for a committer to add a committer.
	AddCommitter(context.Context, *MsgAddCommitter) (*MsgAddCommitterResponse, error)
	// RemoveCommitter defines a method for a committer to remove a committer.
	RemoveCommitter(context.Context, *MsgRemoveCommitter) (*MsgRemoveCommitterResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitProof(ctx context.Context, req *MsgSubmitProof) (*MsgSubmitProofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitProof not implemented")
}
func (*UnimplementedMsgServer) BitcoinTx(ctx context.Context, req *MsgBitcoinTx) (*MsgBitcoinTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BitcoinTx not implemented")
}
func (*UnimplementedMsgServer) TimeoutProposal(ctx context.Context, req *MsgTimeoutProposal) (*MsgTimeoutProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimeoutProposal not implemented")
}
func (*UnimplementedMsgServer) AddCommitter(ctx context.Context, req *MsgAddCommitter) (*MsgAddCommitterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCommitter not implemented")
}
func (*UnimplementedMsgServer) RemoveCommitter(ctx context.Context, req *MsgRemoveCommitter) (*MsgRemoveCommitterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCommitter not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitProof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitProof)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitProof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.ethermint.committer.Msg/SubmitProof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitProof(ctx, req.(*MsgSubmitProof))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BitcoinTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBitcoinTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BitcoinTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.ethermint.committer.Msg/BitcoinTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BitcoinTx(ctx, req.(*MsgBitcoinTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TimeoutProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTimeoutProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TimeoutProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.ethermint.committer.Msg/TimeoutProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TimeoutProposal(ctx, req.(*MsgTimeoutProposal))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddCommitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddCommitter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddCommitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.ethermint.committer.Msg/AddCommitter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddCommitter(ctx, req.(*MsgAddCommitter))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveCommitter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveCommitter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveCommitter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evmos.ethermint.committer.Msg/RemoveCommitter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveCommitter(ctx, req.(*MsgRemoveCommitter))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "evmos.ethermint.committer.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitProof",
			Handler:    _Msg_SubmitProof_Handler,
		},
		{
			MethodName: "BitcoinTx",
			Handler:    _Msg_BitcoinTx_Handler,
		},
		{
			MethodName: "TimeoutProposal",
			Handler:    _Msg_TimeoutProposal_Handler,
		},
		{
			MethodName: "AddCommitter",
			Handler:    _Msg_AddCommitter_Handler,
		},
		{
			MethodName: "RemoveCommitter",
			Handler:    _Msg_RemoveCommitter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ethermint/committer/tx.proto",
}

func (m *MsgSubmitProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndIndex))
		i--
		dAtA[i] = 0x30
	}
	if m.StartIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartIndex))
		i--
		dAtA[i] = 0x28
	}
	if len(m.StateRootHash) > 0 {
		i -= len(m.StateRootHash)
		copy(dAtA[i:], m.StateRootHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StateRootHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ProofHash) > 0 {
		i -= len(m.ProofHash)
		copy(dAtA[i:], m.ProofHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ProofHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitProofResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitProofResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitProofResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgBitcoinTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBitcoinTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBitcoinTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BitcoinTxHash) > 0 {
		i -= len(m.BitcoinTxHash)
		copy(dAtA[i:], m.BitcoinTxHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BitcoinTxHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgBitcoinTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBitcoinTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBitcoinTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgTimeoutProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTimeoutProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTimeoutProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgTimeoutProposalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTimeoutProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTimeoutProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddCommitter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddCommitter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddCommitter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Committer) > 0 {
		i -= len(m.Committer)
		copy(dAtA[i:], m.Committer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Committer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddCommitterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddCommitterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddCommitterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Committer) > 0 {
		i -= len(m.Committer)
		copy(dAtA[i:], m.Committer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Committer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveCommitter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveCommitter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveCommitter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Committer) > 0 {
		i -= len(m.Committer)
		copy(dAtA[i:], m.Committer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Committer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTx(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveCommitterResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveCommitterResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveCommitterResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Committer) > 0 {
		i -= len(m.Committer)
		copy(dAtA[i:], m.Committer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Committer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ProofHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.StateRootHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StartIndex != 0 {
		n += 1 + sovTx(uint64(m.StartIndex))
	}
	if m.EndIndex != 0 {
		n += 1 + sovTx(uint64(m.EndIndex))
	}
	return n
}

func (m *MsgSubmitProofResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgBitcoinTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BitcoinTxHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgBitcoinTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgTimeoutProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgTimeoutProposalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgAddCommitter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Committer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddCommitterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Committer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveCommitter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Committer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveCommitterResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Committer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProofHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRootHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRootHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartIndex", wireType)
			}
			m.StartIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndIndex", wireType)
			}
			m.EndIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitProofResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitProofResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitProofResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBitcoinTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBitcoinTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBitcoinTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BitcoinTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BitcoinTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBitcoinTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBitcoinTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBitcoinTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTimeoutProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTimeoutProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTimeoutProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTimeoutProposalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTimeoutProposalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTimeoutProposalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddCommitter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddCommitter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddCommitter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Committer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Committer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddCommitterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddCommitterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddCommitterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Committer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Committer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveCommitter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveCommitter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveCommitter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Committer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Committer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveCommitterResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveCommitterResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveCommitterResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Committer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Committer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
